# Generated by Django 3.2.13 on 2022-04-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220411_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigninTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signintime', models.DateTimeField(verbose_name='签到时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee', verbose_name='员工')),
            ],
        ),
    ]
